name: Run Static Analysis

on: push

jobs:
  static-analysis:
    runs-on: ${{ matrix.os }}
    name: Static Analysis - OTP ${{ matrix.otp }} | Elixir ${{ matrix.elixir }} | OS ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        otp: [24]
        elixir: [1.14.4]
    services:
      db:
        image: postgres:latest
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: fortymm/end-to-end-tests
          path: 'end-to-end-tests'
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Install dependencies
        run: mix deps.get

      - name: Check for compile warnings
        run: mix compile --warnings-as-errors

      - name: Check formatting
        run: mix format --check-formatted 

      - name: Run unit tests
        run: mix test

      - name: Start web server
        run: |
          mix ecto.setup
          mix phx.server &

      - name: Run end-to-end tests
        working-directory: end-to-end-tests
        run: |
          npm install --force
          npx playwright install --with-deps
          npm run test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: end-to-end-tests/playwright-report/
          retention-days: 30